#!/bin/bash

sudo -s <<'EOF'

	wireTest=$(wg show 2>&1)
	
	if [[ -z "$wireTest" ]]; then 
		cd /etc/wireguard/
		mullConf=$(ls --ignore="*.zip" -1 | shuf -n 1 | cut -d "." -f 1)
		echo ">> Will connect to Mullvad VPN: $mullConf"
		wg-quick up "$mullConf"
		curl https://am.i.mullvad.net/connected
	else
		connConf=$( echo "$wireTest" | grep -Eio "(interface.+)" | sed 's/interface:\s//')	
		echo ">> Hey 'all-around cool person,' you are already connected to Mullvad VPN: $connConf"
	fi

EOF
