#!/bin/bash

sudo -s <<'EOF'

	cd /etc/wireguard

	downConf=$(wg show | grep -Eio "(interface.+)" | sed 's/interface:\s//')
	
	echo "$downConf"
	echo ">> You are connected to Mullvad VPN: $downConf"

	echo ">> Proceeding to disconnect."

	wg-quick down "$downConf"

	curl https://am.i.mullvad.net/connected

EOF
